//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalestrApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prenotazione
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public int IdPalestra { get; set; }
        public System.DateTime OraInizio { get; set; }
        public System.DateTime OraFine { get; set; }
        public bool Attrezzato { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual Palestre Palestre { get; set; }
    }
}
